"""Create initial schemas for users, clients, and audit logs

Revision ID: 07ec9e9b9bff
Revises: 
Create Date: 2025-08-02 12:49:22.641858

"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "07ec9e9b9bff"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("users",
    sa.Column("email", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column("role", sa.Enum("SYSADMIN", "ADMIN", "USER", name="userrole"), nullable=False),
    sa.Column("is_active", sa.Boolean(), nullable=False),
    sa.Column("totp_enabled", sa.Boolean(), nullable=False),
    sa.Column("last_login", sa.DateTime(), nullable=True),
    sa.Column("user_id", sa.Uuid(), nullable=False),
    sa.Column("created_at", sa.DateTime(), nullable=False),
    sa.Column("updated_at", sa.DateTime(), nullable=True),
    sa.Column("password_hash", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column("totp_secret", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.PrimaryKeyConstraint("user_id")
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table("agent1_clients",
    sa.Column("full_name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column("ssn", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column("birth_date", sa.Date(), nullable=False),
    sa.Column("status", sa.Enum("ACTIVE", "INACTIVE", "ARCHIVED", name="clientstatus"), nullable=False),
    sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column("client_id", sa.Uuid(), nullable=False),
    sa.Column("created_at", sa.DateTime(), nullable=False),
    sa.Column("updated_at", sa.DateTime(), nullable=True),
    sa.Column("created_by", sa.Uuid(), nullable=False),
    sa.Column("updated_by", sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(["created_by"], ["users.user_id"], ),
    sa.ForeignKeyConstraint(["updated_by"], ["users.user_id"], ),
    sa.PrimaryKeyConstraint("client_id")
    )
    op.create_table("audit_logs",
    sa.Column("audit_id", sa.Uuid(), nullable=False),
    sa.Column("created_at", sa.DateTime(), nullable=False),
    sa.Column("updated_at", sa.DateTime(), nullable=True),
    sa.Column("table_name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column("record_id", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column("action", sa.Enum("CREATE", "UPDATE", "DELETE", "VIEW", name="auditaction"), nullable=False),
    sa.Column("old_values", sa.JSON(), nullable=True),
    sa.Column("new_values", sa.JSON(), nullable=True),
    sa.Column("user_id", sa.Uuid(), nullable=False),
    sa.Column("ip_address", sqlmodel.sql.sqltypes.AutoString(length=45), nullable=False),
    sa.Column("user_agent", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column("timestamp", sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(["user_id"], ["users.user_id"], ),
    sa.PrimaryKeyConstraint("audit_id")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("audit_logs")
    op.drop_table("agent1_clients")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")

    # Drop enum types
    op.execute("DROP TYPE IF EXISTS auditaction")
    op.execute("DROP TYPE IF EXISTS clientstatus")
    op.execute("DROP TYPE IF EXISTS userrole")
    # ### end Alembic commands ###
