# Pre-commit hooks configuration
# See https://pre-commit.com for more information
repos:
  # General hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable

  # Python hooks (for backend)
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.1.8
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        files: ^apps/api/
      - id: ruff-format
        files: ^apps/api/

  # Python type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.7.1
    hooks:
      - id: mypy
        files: ^apps/api/src/
        additional_dependencies: [types-redis, types-requests]

  # Frontend hooks
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.56.0
    hooks:
      - id: eslint
        files: ^apps/web/
        types: [file]
        types_or: [javascript, jsx, ts, tsx]
        additional_dependencies:
          - eslint@^8.55.0
          - eslint-config-next@^15.4.5
          - "@typescript-eslint/eslint-plugin@^6.0.0"
          - "@typescript-eslint/parser@^6.0.0"

  # Prettier for frontend
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        files: ^apps/web/
        types_or: [javascript, jsx, ts, tsx, json, yaml, markdown]
        additional_dependencies:
          - prettier@^3.1.0
          - prettier-plugin-tailwindcss@^0.5.7

  # Dockerfile linting
  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
      - id: hadolint-docker
        args: [--config, .hadolint.yaml]

  # Commit message linting
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.13.0
    hooks:
      - id: commitizen
        stages: [commit-msg]

# Global excludes
exclude: |
  (?x)^(
    \.git/|
    \.vscode/|
    \.idea/|
    node_modules/|
    \.next/|
    dist/|
    build/|
    coverage/|
    \.turbo/|
    \.pytest_cache/|
    \.mypy_cache/|
    \.ruff_cache/|
    \.DS_Store|
    Thumbs\.db|
    .*\.min\.(js|css)|
    package-lock\.json|
    yarn\.lock|
    pnpm-lock\.yaml
  )