"""Add TOTP backup codes to users table

Revision ID: 5522e7954293
Revises: 07ec9e9b9bff
Create Date: 2025-08-02 15:13:54.123656

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5522e7954293"
down_revision: str | Sequence[str] | None = "07ec9e9b9bff"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("totp_backup_codes", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "totp_backup_codes")
    # ### end Alembic commands ###
