"""add user_id, template_type, status to questionnaire_drafts

Revision ID: 03fe9a42403e
Revises: f0d0004cd787
Create Date: 2025-07-30 21:53:22.785428

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '03fe9a42403e'
down_revision = 'f0d0004cd787'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns with defaults to handle existing data
    op.add_column('questionnaire_drafts', sa.Column('template_type', sa.String(length=100), nullable=False, server_default='standard'))
    op.add_column('questionnaire_drafts', sa.Column('status', sa.String(length=50), nullable=False, server_default='draft'))

    # Add user_id column as nullable first, then update and make not nullable
    op.add_column('questionnaire_drafts', sa.Column('user_id', sa.UUID(), nullable=True))

    # Get first user id to use as default (or could create a system user)
    connection = op.get_bind()
    result = connection.execute(sa.text("SELECT id FROM users LIMIT 1"))
    first_user = result.fetchone()

    if first_user:
        # Update existing records with first user
        connection.execute(sa.text(f"UPDATE questionnaire_drafts SET user_id = '{first_user[0]}' WHERE user_id IS NULL"))

    # Now make user_id NOT NULL and add foreign key
    op.alter_column('questionnaire_drafts', 'user_id', nullable=False)
    op.create_foreign_key(None, 'questionnaire_drafts', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'questionnaire_drafts', type_='foreignkey')
    op.drop_column('questionnaire_drafts', 'status')
    op.drop_column('questionnaire_drafts', 'template_type')
    op.drop_column('questionnaire_drafts', 'user_id')
    # ### end Alembic commands ###
