"""add cascade delete and performance indexes to questionnaire_drafts

Revision ID: 60130784df83
Revises: c9e1947bae30
Create Date: 2025-07-31 19:32:20.399054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60130784df83'
down_revision = 'c9e1947bae30'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('questionnaire_drafts_user_id_fkey'), 'questionnaire_drafts', type_='foreignkey')
    op.drop_constraint(op.f('questionnaire_drafts_client_id_fkey'), 'questionnaire_drafts', type_='foreignkey')
    op.create_foreign_key(None, 'questionnaire_drafts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'questionnaire_drafts', 'clients', ['client_id'], ['id'], ondelete='CASCADE')
    
    # Add performance indexes
    op.create_index('idx_questionnaire_drafts_client_id', 'questionnaire_drafts', ['client_id'])
    op.create_index('idx_questionnaire_drafts_user_id', 'questionnaire_drafts', ['user_id'])
    op.create_index('idx_questionnaire_drafts_status', 'questionnaire_drafts', ['status'])
    op.create_index('idx_questionnaire_drafts_template_type', 'questionnaire_drafts', ['template_type'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop performance indexes
    op.drop_index('idx_questionnaire_drafts_template_type', 'questionnaire_drafts')
    op.drop_index('idx_questionnaire_drafts_status', 'questionnaire_drafts')
    op.drop_index('idx_questionnaire_drafts_user_id', 'questionnaire_drafts')
    op.drop_index('idx_questionnaire_drafts_client_id', 'questionnaire_drafts')
    
    op.drop_constraint(None, 'questionnaire_drafts', type_='foreignkey')
    op.drop_constraint(None, 'questionnaire_drafts', type_='foreignkey')
    op.create_foreign_key(op.f('questionnaire_drafts_client_id_fkey'), 'questionnaire_drafts', 'clients', ['client_id'], ['id'])
    op.create_foreign_key(op.f('questionnaire_drafts_user_id_fkey'), 'questionnaire_drafts', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###