"""sync document model schema

Revision ID: c3a2bfde93e6
Revises: 60130784df83
Create Date: 2025-07-31 21:18:58.539159

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
try:
    import pgvector.sqlalchemy
except ImportError:
    pgvector = None

# revision identifiers, used by Alembic.
revision = 'c3a2bfde93e6'
down_revision = '60130784df83'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('action', sa.Enum('user_created', 'user_updated', 'user_deleted', 'user_2fa_reset', 'user_role_changed', 'agent_started', 'agent_stopped', 'agent_restarted', 'agent_config_updated', 'agent_config_rollback', 'system_health_check', 'system_metrics_accessed', 'system_restart_all_agents', 'login_success', 'login_failed', 'logout', 'session_expired', 'audit_logs_exported', 'users_list_accessed', 'document_uploaded', 'document_processed', 'document_deleted', name='auditaction'), nullable=False),
    sa.Column('level', sa.Enum('info', 'warning', 'error', 'critical', name='auditlevel'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('resource_type', sa.String(length=100), nullable=True),
    sa.Column('resource_id', sa.String(length=255), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('action_timestamp', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_action_timestamp'), 'audit_logs', ['action_timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_level'), 'audit_logs', ['level'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_id'), 'audit_logs', ['resource_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_type'), 'audit_logs', ['resource_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_username'), 'audit_logs', ['username'], unique=False)
    op.create_table('agent_executions',
    sa.Column('execution_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('input_data', sa.JSON(), nullable=True),
    sa.Column('output_data', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('execution_duration', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('execution_id')
    )
    op.create_index(op.f('ix_agent_executions_agent_id'), 'agent_executions', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_executions_status'), 'agent_executions', ['status'], unique=False)
    op.create_table('document_chunks',
    sa.Column('node_id', sa.String(length=255), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768) if pgvector else sa.TEXT(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('chunk_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_chunks_document_id'), 'document_chunks', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_chunks_node_id'), 'document_chunks', ['node_id'], unique=True)
    op.add_column('documents', sa.Column('task_id', sa.String(length=255), nullable=True))
    op.add_column('documents', sa.Column('agent_execution_id', sa.UUID(), nullable=True))
    op.alter_column('documents', 'document_type',
               existing_type=postgresql.ENUM('simple', 'complex', name='documenttype'),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('documents', 'status',
               existing_type=postgresql.ENUM('pending', 'processing', 'processed', 'failed', name='documentstatus'),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.create_index(op.f('ix_documents_content_hash'), 'documents', ['content_hash'], unique=False)
    op.create_foreign_key(None, 'documents', 'agent_executions', ['agent_execution_id'], ['execution_id'])
    op.add_column('questionnaire_drafts', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('questionnaire_drafts', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_index('idx_questionnaire_drafts_client_id', 'questionnaire_drafts', ['client_id'], unique=False)
    op.create_index('idx_questionnaire_drafts_status', 'questionnaire_drafts', ['status'], unique=False)
    op.create_index('idx_questionnaire_drafts_template_type', 'questionnaire_drafts', ['template_type'], unique=False)
    op.create_index('idx_questionnaire_drafts_user_id', 'questionnaire_drafts', ['user_id'], unique=False)
    op.drop_constraint(op.f('questionnaire_drafts_user_id_fkey'), 'questionnaire_drafts', type_='foreignkey')
    op.create_foreign_key(None, 'questionnaire_drafts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('questionnaire_drafts', 'metadata_')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questionnaire_drafts', sa.Column('metadata_', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'questionnaire_drafts', type_='foreignkey')
    op.create_foreign_key(op.f('questionnaire_drafts_user_id_fkey'), 'questionnaire_drafts', 'users', ['user_id'], ['id'])
    op.drop_index('idx_questionnaire_drafts_user_id', table_name='questionnaire_drafts')
    op.drop_index('idx_questionnaire_drafts_template_type', table_name='questionnaire_drafts')
    op.drop_index('idx_questionnaire_drafts_status', table_name='questionnaire_drafts')
    op.drop_index('idx_questionnaire_drafts_client_id', table_name='questionnaire_drafts')
    op.alter_column('questionnaire_drafts', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('questionnaire_drafts', 'metadata')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_index(op.f('ix_documents_content_hash'), table_name='documents')
    op.alter_column('documents', 'status',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('pending', 'processing', 'processed', 'failed', name='documentstatus'),
               existing_nullable=False)
    op.alter_column('documents', 'document_type',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('simple', 'complex', name='documenttype'),
               existing_nullable=False)
    op.drop_column('documents', 'agent_execution_id')
    op.drop_column('documents', 'task_id')
    op.drop_index(op.f('ix_document_chunks_node_id'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_document_id'), table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index(op.f('ix_agent_executions_status'), table_name='agent_executions')
    op.drop_index(op.f('ix_agent_executions_agent_id'), table_name='agent_executions')
    op.drop_table('agent_executions')
    op.drop_index(op.f('ix_audit_logs_username'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_level'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###