"""add_audit_logs_table

Revision ID: c9e1947bae30
Revises: 35e370fcce94
Create Date: 2025-07-31 13:14:40.604482

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = 'c9e1947bae30'
down_revision = '35e370fcce94'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('action', sa.Enum('user_created', 'user_updated', 'user_deleted', 'user_2fa_reset', 'user_role_changed', 'agent_started', 'agent_stopped', 'agent_restarted', 'agent_config_updated', 'agent_config_rollback', 'system_health_check', 'system_metrics_accessed', 'system_restart_all_agents', 'login_success', 'login_failed', 'logout', 'session_expired', 'audit_logs_exported', 'users_list_accessed', 'document_uploaded', 'document_processed', 'document_deleted', name='auditaction'), nullable=False),
    sa.Column('level', sa.Enum('info', 'warning', 'error', 'critical', name='auditlevel'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('resource_type', sa.String(length=100), nullable=True),
    sa.Column('resource_id', sa.String(length=255), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('action_timestamp', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_action_timestamp'), 'audit_logs', ['action_timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_level'), 'audit_logs', ['level'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_id'), 'audit_logs', ['resource_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_type'), 'audit_logs', ['resource_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_username'), 'audit_logs', ['username'], unique=False)
    op.drop_index(op.f('idx_questionnaire_drafts_client_id'), table_name='questionnaire_drafts')
    op.drop_index(op.f('idx_questionnaire_drafts_user_id'), table_name='questionnaire_drafts')
    op.drop_constraint(op.f('questionnaire_drafts_client_id_fkey'), 'questionnaire_drafts', type_='foreignkey')
    op.drop_constraint(op.f('questionnaire_drafts_user_id_fkey'), 'questionnaire_drafts', type_='foreignkey')
    op.create_foreign_key(None, 'questionnaire_drafts', 'clients', ['client_id'], ['id'])
    op.create_foreign_key(None, 'questionnaire_drafts', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'questionnaire_drafts', type_='foreignkey')
    op.drop_constraint(None, 'questionnaire_drafts', type_='foreignkey')
    op.create_foreign_key(op.f('questionnaire_drafts_user_id_fkey'), 'questionnaire_drafts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('questionnaire_drafts_client_id_fkey'), 'questionnaire_drafts', 'clients', ['client_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_questionnaire_drafts_user_id'), 'questionnaire_drafts', ['user_id'], unique=False)
    op.create_index(op.f('idx_questionnaire_drafts_client_id'), 'questionnaire_drafts', ['client_id'], unique=False)
    op.drop_index(op.f('ix_audit_logs_username'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_level'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
